version: '3.8'

services:
  esx2-proxy:
    image: nginx:alpine
    container_name: esx2-proxy
    restart: always
    networks:
      - nginx-net
    environment:
      - VIRTUAL_HOST=esx2.itsmillan.com
      - LETSENCRYPT_HOST=esx2.itsmillan.com
      - LETSENCRYPT_EMAIL=admin@itsmillan.com
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  nginx-net:
    external: true
